### ISSUE TITLE
Mixer update issues again

### ISSUE THREAD

**Issue by dereuromark** [CakeDC/mixer#37]
[x] Bug

https://github.com/dereuromark/cakephp-ide-helper/releases has been released two days ago.
But it never shows up in "New Releases"
There are some of 5 days and 1 hour ago, seems to be missing a lot in between though.

![screenshot from 2018-04-09 16-04-10](https://user-images.githubusercontent.com/39854/38502442-ad263eea-3c0f-11e8-9ffd-61e57356068f.png)

**Comment by andrej-griniuk** [comment]
Ok so the problem is that we're actually using latest tag date, not release date, cause I thought that's more valuable, cause not everyone creates releases for every tag and from other side release can't be created without a tag. In this case 0.11.2 release is 3 days old, but 0.11.2 tag is 12 days old. 

Not sure what to do. Do you think we should rather track releases only?

**Comment by dereuromark** [comment]
I see. But both were creating from github the same day :) Must be a git issue on the tag being the date of the last dev-master commit.

Well, the actual releases are usually the ones people can then pull and use. dev-master commits etc are usually more a test-run. So yeah, I think actual releases would be more valuable.
But if this is harder to do, then we can also just keep current behavior.
